exports.getQuotes = function(){
    return {
        quotes: [
            "When a bird hits your window have you ever wondered if God is playing angry birds with you?",
            "I’m an excellent housekeeper. Every time I get a divorce, I keep the house.",
            "I look at people sometimes and think ….. Really?? That’s the sperm that won.",
            "I hate when people all of a sudden decide to be funny when I am drinking something.",
            "God made everything that has life, rest everything is made in China.",
            "Sometimes you just need some space............To fart.",
            "I wake up when I cant hold my pee in any longer.",
            "Behind every great woman is a man looking at her ass!",
            "If women ruled the world there would be no wars. Just a bunch of jealous countries not talking to each other.",
            "I like to name my&nbsp;iPod&nbsp;‘Titanic’ so when it says ‘Syncing Titanic’ i click cancel and it makes me feel like a&nbsp;hero.",
            "If you think nobody cares if you’re alive, try missing a couple of car payments.",
            "Whenever i have a problem, I just sing, Then i realize my voice is worse than my problem.",
            "Women should not have children after 35. Really… 35 children are enough.",
            "I&nbsp;remember&nbsp;the time I was kidnapped and they sent a piece of my finger to my father. He said he needs more&nbsp;proof.",
            "That awkward moment when you realize that “deleting History” is more important than “creating History” nowadays.",
            "Fart when people hug you. It makes them feel strong.",
            "If you can't Change a Girl.....Change the Girl.",
            "When I’m on my death bed, I want my final words to be “I left one million dollars in the…",
            "I think my iPhone is broken. I pressed the home button and i’m still at school.",
            "Dear Lord, all I ask for a chance to prove that winning the lottery won’t make a bad person.",
            "All my life I thought air is free until I bought a bag of chips.",
            "Dear MATH, stop asking to find your X, she’s not coming back.",
            "She is so fake that she should have two facebook accounts; one for each face !!!",
            "That depressing moment when you dip your cookie into milk for too long, it breaks off, and you wonder why bad things happen to good people.",
            "I always learn from mistake of others who take my advice.",
            "Every so often, I like to go to the window, look up, and smile for a satellite picture.",
            "The longer the title the less important the job.",
            "When people go underwater in movies, I like to hold my breath and see if I would have survived in that situation.",
            "I’ve been using Google for 10 years and I have no idea who uses the “I’m Feeling Lucky” button.",
            "Teaching your own mother how to use Facebook is like willingly signing your own death warrant.",
            "Make love, not war. Hell, do both. Get married.",
            "Decided to burn lots of calories today so I set a fat kid on fire!",
            "Bisexuality immediately doubles your chances for a date on Saturday night.",
            "I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.",
            "Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad.",
            "Behind every great man is a woman rolling her eyes.",
            "A little boy asked his father, “Daddy, how much does it cost to get married?” Father replied, “I don’t know son, I’m still paying.”",
            "We all have that one skinny friend that eats more than fat person.",
            "When I die, I want to go peacefully like my Grandfather did, in his sleep — not screaming, like the passengers in his car”",
            "Everyone has an annoying friend. If you don’t have one, it’s probably you.",
            "When a woman says WHAT? Its not because she&nbsp;didn't&nbsp;hear you. She’s giving you a chance to change what&nbsp;you said.",
            "Dear Google, Please stop behaving like a GIRL. Will u please allow me to complete the whole sentence before you start guessing &amp; suggesting."
        ]
    };
};